### ISSUE TITLE
demo using a template?

### ISSUE THREAD

**Issue by davidmaxwaterman** [txsmith/dragula-element#2]
It would be good to have a demo using a template, something like :

```
184           <polymer-dragula id="dragula">
185             <div>
186               <template is="dom-repeat" items="[[_myItemList]]">
187                 <div my-id="[[item.myId]]" class="drop-item">
188                   <div>[[_increment(index)]].</div>
189                   <div>[[item.name]] ([[item.code]])</div>
190                   <div><iron-icon icon="editor:drag-handle"></iron-icon>[[item.text]]</div>
191                 </div>
192               </template>
193             </div>
194           </polymer-dragula>
```

I had to hack polymer-dragula to make this work...here are the relevant bits (`this` is the polymer-dragular element and the following code is in the attached function :

```
84               var template = this.queryEffectiveChildren('div').querySelector('template');
185
186               template.addEventListener('dom-change', e => {
187                 var containers = [Polymer.dom(this).children[0]];
188
189                 if (this.drake) {
190                   this.drake.containers = containers;
191                 } else {
192                   var drake = dragula(containers, config);
```

**Comment by txsmith** [comment]
I've added a property for setting the container class to support the use-case you describe. There is also a demo with this + dom-repeat. Hope this is what you need!

**Comment by davidmaxwaterman** [comment]
I noticed the demo didn't actually add/remove from the dom-repeat's array - it would be nice if the demo included that, just to prove it to someone considering using it - but when I hacked that into the demo, it still worked just fine, so I'm happy :)

FWIW, I added this code :

```
   42             <paper-material item-index="[[index]]" elevation="1" class="item">
...
 68       attached: function() {
 69         var self = this;
 70
 71         this.$.dragula.addEventListener('dragula-drop', function(event) {
 72           console.log('dropped');
 73           var items = this.querySelectorAll('.item');
 74           for (var i=0; i<items.length; i++) {
 75             var item = items[i];
 76             console.log('item:', item.itemIndex);
 77           }
 78         });
 79
 80         this.async(function() {
 81           self.push('dragItems', { title: 'Boo!', subtitle: 'Can you see me?' });
 82         }, 1000);
 83       },
```

If you wanted to consider adding something like that (perhaps an add/remove button would be better).

Your implementation looks better than what I hacked together (shadow/etc work), so I think I'll spend a couple of hours getting it into my real code.

Thanks!

**Comment by davidmaxwaterman** [comment]
Yup, worked fine, once I'd taken out my hacks...much cleaner. Thanks again :)

Is this element in the bower registry? Might be a good idea.

**Comment by txsmith** [comment]
Yeah I'll look into that! I haven't done this yet because it's not as polished as I'd like... But I guess it's fine for an initial version
